language: python
dist: trusty
sudo: required
matrix:
    include:
        - python: 2.7
          env: PYENV=py27
        - python: 3.5
          env: PYENV=py35
        - python: 3.8
          env: PYENV=py38
install:
    - source ci/install.sh
script:  bash ci/test_script.sh
after_success:
  - coveralls
cache:
  directories:
    - $HOME/nest-2.20.0
    - $HOME/nrn-7.7
    - $HOME/build/nest-2.20.0
    - $HOME/build/nrn-7.7
    - $HOME/.cache/pip
